### ISSUE TITLE
error Connection refused

### ISSUE THREAD

**Issue by nmta** [edwindj/cbsodata.R#14] opened 2018-06-20 08:54 UTC
Hi, 
I am trying to pull out data but it seems I have a problem with the proxy and I get this error. 

tables_en <- cbs_get_toc(Language="en")
Error in curl::curl_fetch_memory(url, handle = handle) : 
Failed to connect to opendata.cbs.nl port 443: Connection refused

Could you help me to get a solution to it?
Best,

Nmta

**Comment by edwindj** [comment] 2018-06-20 13:26
Dear nmta,

Thanks for reporting: your error may be caused by your network/proxy configuration.
1. Could you send me your sessionInfo(()
2. The problem may be solved in the latest development version of cbsodataR, which I'm in the process of sending to CRAN. Is it possible for you to run 
```R
devtools::install_github("edwindj/cbsodataR")
```
and check if it is working for you now?
Thanks in advance!

Best,

Edwin

**Comment by nmta** [comment] 2018-06-20 14:03
Dear edwindj, 
Thanks a lot for your message, indeed i believe there is a proxy problem with curl.

-I tried this ;

Sys.setenv(TZ = "Europe/Amsterdam") 
library(curl) 
library(cbsodataR)
cbsodataR::cbs_get_data(id="7196ENG", Periods="2000MM03", CPI="000000")

-Got the following error:
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failed to connect to opendata.cbs.nl port 443: Connection refused

-My session info is the following:
sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_Ireland.1252  LC_CTYPE=English_Ireland.1252    LC_MONETARY=English_Ireland.1252 LC_NUMERIC=C                     LC_TIME=English_Ireland.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] cbsodataR_0.3 curl_3.2     

loaded via a namespace (and not attached):
[1] httr_1.3.1     compiler_3.4.1 R6_2.2.2       tools_3.4.1    whisker_0.3-2  jsonlite_1.5

**Comment by nmta** [comment] 2018-06-20 14:03
Thanks in advance , 
nmta

**Comment by edwindj** [comment] 2018-08-16 16:21
I cannot reproduce your error. I suspect that `httr` and `curl` on which cbsodataR relies solved the issue, could you update these packages and check if that solves your problem?

**Comment by edwindj** [comment] 2019-08-09 08:26
Closing issue, please reopen if necessary

**Closed as completed by edwindj** 2019-08-09 08:26 UTC
